# -*- coding: utf-8 -*-
"""Mapreduce Hadoop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SmdZ3Qn-lId5ueTnURoNC4VykQspRDg
"""

#Set up google colab
!apt-get update
!apt-get install -y openjdk-8-jdk
!wget https://downloads.apache.org/hadoop/common/hadoop-3.3.5/hadoop-3.3.5.tar.gz
!tar -xzvf hadoop-3.3.5.tar.gz
!mv hadoop-3.3.5 /usr/local/hadoop
!pip install -q mrjob

#set environment variables
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["HADOOP_HOME"] = "/usr/local/hadoop"
os.environ["PATH"] += ":/usr/local/hadoop/bin:/usr/local/hadoop/sbin"

#copy paste teks pembukaan UUD 1945"
text = "Bahwa sesungguhnya Kemerdekaan itu ialah hak segala bangsa dan oleh sebab itu, maka penjajahan di atas dunia harus dihapuskan, karena tidak sesuai dengan perikemanusiaan dan perikeadilan.Dan perjuangan pergerakan kemerdekaan Indonesia telah sampailah kepada saat yang berbahagia dengan selamat sentausa mengantarkan rakyat Indonesia ke depan pintu gerbang kemerdekaan Negara Indonesia, yang merdeka, bersatu, berdaulat, adil dan makmur.Atas berkat rakhmat Allah Yang Maha Kuasa dan dengan didorongkan oleh keinginan luhur, supaya berkehidupan kebangsaan yang bebas, maka rakyat Indonesia menyatakan dengan ini kemerdekaannya.Kemudian daripada itu untuk membentuk suatu Pemerintah Negara Indonesia yang melindungi segenap bangsa Indonesia dan seluruh tumpah darah Indonesia dan untuk memajukan kesejahteraan umum, mencerdaskan kehidupan bangsa, dan ikut melaksanakan ketertiban dunia yang berdasarkan kemerdekaan, perdamaian abadi dan keadilan sosial, maka disusunlah Kemerdekaan Kebangsaan Indonesia itu dalam suatu Undang-Undang Dasar Negara Indonesia, yang terbentuk dalam suatu susunan Negara Republik Indonesia yang berkedaulatan rakyat dengan berdasar kepada Ketuhanan Yang Maha Esa, Kemanusiaan yang adil dan beradab, Persatuan Indonesia dan Kerakyatan yang dipimpin oleh hikmat kebijaksanaan dalam Permusyawaratan/Perwakilan, serta dengan mewujudkan suatu Keadilan sosial bagi seluruh rakyat Indonesia."
with open("pembukaan_uud1945.txt", "w") as file:
  file.write(text)

### Membuat `mapper.py` dan `reducer.py`
#1. **Buat File `mapper.py`:**
#```python
!echo -e '#!/usr/bin/env python3\nimport sys\nfor line in sys.stdin:\n    words = line.strip().split()\n    for word in words:\n        print(f"{word.lower()}\t1")' > mapper.py
!chmod +x mapper.py

## file reducer.py
!echo -e '#!/usr/bin/env python3\nimport sys\nfrom collections import defaultdict\nword_count = defaultdict(int)\nfor line in sys.stdin:\n    word, count = line.strip().split("\t")\n    word_count[word] += int(count)\nfor word, count in word_count.items():\n    print(f"{word}\t{count}")' > reducer.py
!chmod +x reducer.py

!hadoop fs -rm -r /output

#hadoop streaming
!hadoop fs -mkdir /input
!hadoop fs -put pembukaan_uud1945.txt /input
!hadoop fs -mkdir /output

!hadoop jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.5.jar \
-input /input/pembukaan_uud1945.txt -output /output_new \
-mapper mapper.py -reducer reducer.py

#memerikan output
!hadoop fs -cat /output_new/part-00000 > output_wordcount.txt

#menyalin output ke local
from google.colab import files
files.download('output_wordcount.txt')